import type { Metadata } from "next";
import { Megaphone, Sparkles } from "lucide-react";

import { SyncButton } from "@/app/(dashboard)/accounts/sync-button";
import { AdRowActions, VariantReviewActions } from "@/app/(dashboard)/ads/ad-actions";
import { PageHeader, SectionHeader } from "@/components/dashboard/page-header";
import { RangePicker } from "@/components/dashboard/range-picker";
import { EntityStatusBadge, StatusBadge } from "@/components/dashboard/status-badge";
import { EmptyState, Surface, SurfaceHeader } from "@/components/dashboard/surface";
import { CellStack, DataTable, NumberCell } from "@/components/tables/data-table";
import { TableSearch } from "@/components/tables/table-toolbar";
import {
  formatCurrency,
  formatDecimal,
  formatNumber,
  formatPercent,
  formatRatio,
  formatRelativeTime,
} from "@/lib/analytics/format";
import { listAdVariants } from "@/lib/ai/ad-copy";
import { getAdPerformance, type AdPerformance } from "@/lib/analytics/queries";
import { can } from "@/lib/auth/rbac";
import {
  loadPageContext,
  resolveSort,
  sortRows,
  withParams,
  type SearchParams,
} from "@/lib/dashboard/page-context";

export const metadata: Metadata = { title: "Ads" };

const SORTABLE = ["name", "cost", "impressions", "ctr", "conversions", "cpa", "roas"] as const;

const STRENGTH_TONE: Record<string, "positive" | "warning" | "negative" | "neutral"> = {
  EXCELLENT: "positive",
  GOOD: "positive",
  AVERAGE: "warning",
  POOR: "negative",
  PENDING: "neutral",
};

export default async function AdsPage({ searchParams }: { searchParams: Promise<SearchParams> }) {
  const params = await searchParams;
  const { auth, scope, range, profitConfig, currency, settings, account } =
    await loadPageContext(params);

  const [all, variants] = await Promise.all([
    getAdPerformance(scope, range, profitConfig, { limit: 300 }),
    listAdVariants(auth.organization.id, account.id),
  ]);

  const query = typeof params.q === "string" ? params.q.trim().toLowerCase() : "";
  const filtered = all.filter((ad) =>
    query
      ? ad.headlines.some((headline) => headline.toLowerCase().includes(query)) ||
        ad.adGroupName.toLowerCase().includes(query) ||
        ad.campaignName.toLowerCase().includes(query)
      : true,
  );

  const sort = resolveSort(params, SORTABLE, { key: "cost", direction: "desc" });
  const rows = sortRows(filtered, sort, {
    name: (row) => row.name.toLowerCase(),
    cost: (row) => row.metrics.cost,
    impressions: (row) => row.metrics.impressions,
    ctr: (row) => row.metrics.ctr,
    conversions: (row) => row.metrics.conversions,
    cpa: (row) => row.metrics.cpa,
    roas: (row) => row.metrics.roas,
  });

  const canAct = can(auth.role, "actions:execute");
  const blockedReason =
    settings.mode === "SUGGESTIONS"
      ? "Drafts are still generated in Suggestions mode, but nothing is published."
      : "Your role cannot apply changes.";

  const buildSortHref = (key: string, direction: "asc" | "desc") =>
    withParams("/ads", params, { sort: key, dir: direction });

  return (
    <div className="space-y-5">
      <PageHeader
        title="Ads"
        description={`${all.length} ads · ${range.label}`}
        actions={
          <>
            <RangePicker preset={range.preset} start={range.start} end={range.end} />
            <SyncButton accountId={account.id} />
          </>
        }
      />

      {variants.length > 0 ? (
        <Surface padded={false}>
          <SurfaceHeader>
            <SectionHeader
              title="Ad drafts"
              description="Generated copy waiting for review. Nothing is live until you publish it."
            />
            <StatusBadge tone="info">{variants.length} waiting</StatusBadge>
          </SurfaceHeader>

          <ul className="divide-y divide-border">
            {variants.map((variant) => {
              const headlines = variant.headlines as string[];
              const descriptions = variant.descriptions as string[];

              return (
                <li key={variant.id} className="space-y-3 px-5 py-4">
                  <div className="flex flex-wrap items-start justify-between gap-3">
                    <div className="min-w-0">
                      <p className="text-[13px] font-medium">{variant.adGroup.name}</p>
                      <p className="mt-0.5 text-[12px] text-muted-foreground">
                        {variant.generatedBy === "deterministic"
                          ? "Generated without a model"
                          : `Generated by ${variant.generatedBy}`}{" "}
                        · {formatRelativeTime(variant.createdAt)}
                      </p>
                    </div>
                    <div className="flex items-center gap-2">
                      {variant.status === "APPROVED" ? (
                        <StatusBadge tone="positive">Approved</StatusBadge>
                      ) : null}
                      <VariantReviewActions
                        variantId={variant.id}
                        status={variant.status}
                        canAct={canAct}
                      />
                    </div>
                  </div>

                  <div className="grid gap-3 sm:grid-cols-2">
                    <div>
                      <p className="text-[11px] font-medium tracking-wide text-muted-foreground uppercase">
                        Headlines
                      </p>
                      <ul className="mt-1.5 space-y-1">
                        {headlines.map((headline, index) => (
                          <li
                            key={`${variant.id}-h-${index}`}
                            className="flex items-baseline justify-between gap-3 text-[13px]"
                          >
                            <span className="truncate">{headline}</span>
                            <span className="tabular shrink-0 text-[11px] text-muted-foreground">
                              {headline.length}/30
                            </span>
                          </li>
                        ))}
                      </ul>
                    </div>
                    <div>
                      <p className="text-[11px] font-medium tracking-wide text-muted-foreground uppercase">
                        Descriptions
                      </p>
                      <ul className="mt-1.5 space-y-1">
                        {descriptions.map((description, index) => (
                          <li
                            key={`${variant.id}-d-${index}`}
                            className="flex items-baseline justify-between gap-3 text-[13px]"
                          >
                            <span className="truncate">{description}</span>
                            <span className="tabular shrink-0 text-[11px] text-muted-foreground">
                              {description.length}/90
                            </span>
                          </li>
                        ))}
                      </ul>
                    </div>
                  </div>

                  {variant.rationale ? (
                    <p className="rounded-lg bg-muted px-3.5 py-2.5 text-[12px] leading-5 text-muted-foreground">
                      {variant.rationale}
                    </p>
                  ) : null}
                </li>
              );
            })}
          </ul>
        </Surface>
      ) : null}

      <Surface padded={false}>
        <SurfaceHeader className="gap-3">
          <SectionHeader
            title="Live ads"
            description="Sorted by spend. Generate a variant to test a different angle."
          />
          <TableSearch placeholder="Search ads" />
        </SurfaceHeader>

        <DataTable<AdPerformance>
          sort={sort}
          buildSortHref={buildSortHref}
          rows={rows}
          rowKey={(row) => row.id}
          columns={[
            {
              key: "name",
              header: "Ad",
              sortable: true,
              render: (row) => (
                <CellStack
                  primary={row.headlines.slice(0, 2).join(" · ") || row.name}
                  secondary={`${row.campaignName} › ${row.adGroupName}`}
                />
              ),
            },
            {
              key: "adStrength",
              header: "Strength",
              hideBelow: "lg",
              width: "104px",
              render: (row) =>
                row.adStrength ? (
                  <StatusBadge tone={STRENGTH_TONE[row.adStrength] ?? "neutral"}>
                    {row.adStrength.charAt(0) + row.adStrength.slice(1).toLowerCase()}
                  </StatusBadge>
                ) : (
                  <span className="text-[12px] text-muted-foreground">—</span>
                ),
            },
            {
              key: "status",
              header: "Status",
              hideBelow: "xl",
              width: "92px",
              render: (row) => <EntityStatusBadge status={row.status} />,
            },
            {
              key: "impressions",
              header: "Impr.",
              align: "right",
              sortable: true,
              hideBelow: "xl",
              render: (row) => (
                <NumberCell value={formatNumber(row.metrics.impressions, { compact: true })} muted />
              ),
            },
            {
              key: "ctr",
              header: "CTR",
              align: "right",
              sortable: true,
              hideBelow: "sm",
              render: (row) => (
                <NumberCell value={formatPercent(row.metrics.ctr, { decimals: 2 })} />
              ),
            },
            {
              key: "cost",
              header: "Spend",
              align: "right",
              sortable: true,
              render: (row) => <NumberCell value={formatCurrency(row.metrics.cost, currency)} />,
            },
            {
              key: "conversions",
              header: "Conv.",
              align: "right",
              sortable: true,
              render: (row) => <NumberCell value={formatDecimal(row.metrics.conversions, 1)} />,
            },
            {
              key: "roas",
              header: "ROAS",
              align: "right",
              sortable: true,
              hideBelow: "md",
              render: (row) => (
                <NumberCell
                  value={formatRatio(row.metrics.roas)}
                  className={
                    settings.targetRoas && row.metrics.roas
                      ? row.metrics.roas >= settings.targetRoas
                        ? "text-positive"
                        : "text-negative"
                      : undefined
                  }
                />
              ),
            },
            {
              key: "actions",
              header: "",
              align: "right",
              width: "128px",
              render: (row) => (
                <AdRowActions
                  adRowId={row.id}
                  canAct={canAct}
                  isPaused={row.status === "PAUSED"}
                  blockedReason={blockedReason}
                />
              ),
            },
          ]}
          emptyState={
            <EmptyState
              icon={Megaphone}
              title={query ? "No ads match" : "No ads yet"}
              description={
                query
                  ? "Try a different search."
                  : "Responsive search ads appear here after the first sync, with their headlines, ad strength and performance."
              }
            />
          }
        />
      </Surface>

      <div className="flex items-start gap-2.5 rounded-lg border border-border bg-card px-4 py-3">
        <Sparkles className="mt-0.5 size-4 shrink-0 text-primary" aria-hidden />
        <p className="text-[12px] leading-5 text-muted-foreground">
          Generated copy reuses the angles already in your ads and never invents an offer, a price
          or a claim. Character counts are checked before publishing, and a published variant is
          added alongside your current ads so Google can rotate them — nothing is replaced.
        </p>
      </div>
    </div>
  );
}
